'use client';
import {useCallback,useEffect,useState} from 'react';
import PilotPreparation from './pilot-preparation';
import {apiFetch} from '../lib/client-api';
import {ISSUE_CATEGORIES,feedbackStatus} from '../lib/beta';
type Report={id:string;bookTitle:string;category:keyof typeof ISSUE_CATEGORIES;message:string;chapterLabel:string;device:string;appVersion:string;status:keyof typeof feedbackStatus;createdAt:string};
type Data={activity:{activeReaders:number;returningReaders:number};counts:{reports:number;unresolved:number};failures:{event:string;count:number}[];feedback:Report[];reviews:{id:string;bookTitle:string;rating:number;textRating:number;comment:string}[];books:{id:string;title:string;readers:number;advanced:number;completed:number;storyRating:number|null;textRating:number|null;ratings:number}[]};
const errorNames:Record<string,string>={reader_open_failed:'Falha ao abrir livro',chapter_load_failed:'Falha ao carregar capítulo',sync_failed:'Falha ao sincronizar'};
export default function BetaDashboard(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('pending');
 const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await apiFetch('/api/admin/beta',{cache:'no-store'});if(!r.ok){if(r.status===403)window.dispatchEvent(new Event('sambu-master-locked'));throw new Error('Não foi possível atualizar o painel. Verifique seu acesso e tente novamente.');}setData(await r.json());}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();},[load]);
 return <section className="beta-dashboard"><PilotPreparation/><div className="feedback-actions"><h2>Acompanhamento do beta</h2><button className="outline" disabled={busy} onClick={load}>{busy?'Atualizando…':'Atualizar indicadores'}</button></div>{error&&<p role="alert">{error}</p>}
 {data&&<><p>Atividade dos últimos 14 dias. A coleta começa nesta atualização; os dias são contados em UTC.</p><div className="beta-metrics"><div><strong>{data.activity.activeReaders}</strong><span>Leitores que abriram livros</span></div><div><strong>{data.activity.returningReaders}</strong><span>Leram em dois ou mais dias</span></div><div><strong>{data.counts.unresolved}</strong><span>Relatos pendentes, desde o início</span></div><div><strong>{data.activity.activeReaders?`${Math.round(data.activity.returningReaders/data.activity.activeReaders*100)}%`:'—'}</strong><span>Retorno em outro dia no período</span></div></div>
 <h3>Leitura e qualidade por livro</h3><p>“Avançaram” e “Concluíram” usam o progresso atual de quem abriu o livro no período. Notas de 1 a 5 incluem todas as avaliações do beta. A lista mostra até 200 obras.</p><div className="admin-table-wrap"><table><thead><tr><th>Livro</th><th>Leitores</th><th>Avançaram ≥25%</th><th>Concluíram</th><th>História</th><th>Texto</th><th>Avaliações</th></tr></thead><tbody>{data.books.map(b=><tr key={b.id}><td>{b.title}</td><td>{b.readers}</td><td>{b.advanced}</td><td>{b.completed}</td><td>{b.storyRating??'—'}</td><td>{b.textRating??'—'}</td><td>{b.ratings}</td></tr>)}</tbody></table></div>
 <h3>Falhas registradas</h3><p>Uma ocorrência por conta, livro, tipo e dia. Falhas sem conexão podem não chegar ao painel.</p>{data.failures.length?<ul>{data.failures.map(f=><li key={f.event}>{errorNames[f.event]}: {f.count}</li>)}</ul>:<p>Nenhuma falha registrada no período.</p>}
 <h3>Relatos dos leitores</h3><label>Mostrar <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pendentes</option><option value="all">Todos</option><option value="resolved">Resolvidos</option></select></label><p>Até 100 relatos, com pendentes primeiro. Um relato de desinteresse é uma opinião do leitor; não inferimos o motivo do abandono apenas pelo progresso.</p>
 {!data.feedback.filter(f=>filter==='all'||(filter==='pending'?f.status!=='resolved':f.status==='resolved')).length&&<p>Nenhum relato neste filtro.</p>}
 {data.feedback.filter(f=>filter==='all'||(filter==='pending'?f.status!=='resolved':f.status==='resolved')).map(f=><article className="beta-report" key={f.id}><h4>{f.bookTitle||'Livro removido'} · {ISSUE_CATEGORIES[f.category]}</h4><p>{f.message}</p><small>{f.chapterLabel||'Posição informada'} · {f.device==='mobile'?'Celular':'Computador'} · {new Date(f.createdAt).toLocaleString('pt-BR')} · {f.appVersion}</small><label>Situação<select aria-label={`Situação do relato: ${f.message}`} value={f.status} disabled={busy} onChange={async e=>{const status=e.target.value;setBusy(true);setError('');try{const r=await apiFetch('/api/admin/beta',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:f.id,status})});if(!r.ok)throw new Error();await load();}catch{setError('Não foi possível mudar a situação. Tente novamente.');}finally{setBusy(false);}}}>{Object.entries(feedbackStatus).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></article>)}
 <h3>Comentários sobre os livros</h3><p>Últimas 100 avaliações. Uma avaliação por conta e livro, que o leitor pode atualizar.</p>{data.reviews.length?data.reviews.map(r=><article className="beta-report" key={r.id}><h4>{r.bookTitle}</h4><p>História: {r.rating}/5 · Texto: {r.textRating}/5</p>{r.comment&&<p>{r.comment}</p>}</article>):<p>Ainda não há avaliações.</p>}
 </>}
 </section>;
}
